### PR TITLE
Fix round robin rule

### PR DESCRIPTION
**Pull request by MikaelCluseau**
Hi, the probabilistic round robin iptables rule had a few problems. Here are the fixes.

### CODE REVIEW

**Comment by BenTheElder** [comment]
LGTM, Thanks!

**Comment by MikaelCluseau** [comment]
Hi again, issues are not open here, so I'm just adding a comment on this PR.

I'm looking forward to replace my quick-and-dirty ruby implementation with yours.

From my tests, pod-to-pod networking through service IPs doesn't work. I'm pretty sure it's because the packet are not SNATed:

```
$ time curl -i mail.master
HTTP/1.1 404 Not Found
Content-Type: application/octet-stream
Content-Length: 58
Server: Jetty(9.2.9.v20150224)

Could not find resource for full path: http://mail.master/
real	0m0.019s
user	0m0.008s
sys	0m0.000s
$ kubectl --namespace=master exec keystone-zdr02 -- wget mail
--2015-07-11 00:08:44--  http://mail/
Resolving mail (mail)... 10.107.140.79
Connecting to mail (mail)|10.107.140.79|:80... failed: Connection timed out.
Retrying.
```

I'll try to add a MASQERADE rule. I know this will hide the real source IP from the pod, but it's not worse than with the original proxy ;)

**Comment by BenTheElder** [comment]
Hi, Issue should be open now, sorry about that.

For the pod-to-pod networking; I'm not sure why that's not working but I'll do whatever I can to fix it, I only have the e2e clusters on vagrant for testing, as I'm not an end-user of kubernetes myself.

I think @thockin [wanted](https://github.com/GoogleCloudPlatform/kubernetes/issues/3760#issue-55311134) to preserve the source IP's but if we cannot do that, working networking would of course be better than none.

**Comment by BenTheElder** [comment]
I see you used `MASQUERADE` rules successfully in your ruby implementation which otherwise looks to have pretty similar rules and behavior (?)

@thockin, any thoughts on this?

**Comment by MikaelCluseau** [comment]
Yes, I'm very close to your behavior, I just didn't use `-m recent`.

**Comment by BenTheElder** [comment]
Yes, those would be from thockin's rules on the first post at the `use iptables for proxying instead of userspace` issue on kubernetes upstream for doing sticky sessions.

**Pull request merged**
